name: Compile Arduino Sketch for ESP8266

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Arduino CLI
    - name: Install Arduino CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        mv bin/arduino-cli /usr/local/bin/

    # Install ESP8266 core
    - name: Install ESP8266 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266

    # Compile the Chunkk-quizz.ino file for ESP8266
    - name: Compile Arduino sketch for ESP8266
      run: |
        arduino-cli compile --fqbn esp8266:esp8266:esp8266 ./Chunkk-quizz.ino --output-dir ./build

    # Upload the compiled binary as a release asset
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/Chunkk-quizz.ino.bin
        asset_name: Chunkk-quizz.ino.bin
        asset_content_type: application/octet-stream
